apiVersion: v1
kind: Service
metadata:
  name: cheeseshop-static-service
spec:
  ports:
  - port: 8082
    protocol: TCP
    name: cheeseshop-static
  selector:
    app: cheeseshop-static
---
apiVersion: v1
kind: Service
metadata:
  name: cheeseshop-webapp-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    name: cheeseshop-webapp
  selector:
    app: cheeseshop-webapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cheeseshop-static
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cheeseshop-static
    spec:
      containers:
      - name: cheeseshop-static
        image: container-registry.dev.ibmesports.com/cheeseshop-static:$IMAGE_TAG
        imagePullPolicy: Always
        env:
        - name: NGINX_LISTEN
          value: "*:8082"
        ports:
        - containerPort: 8082
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cheeseshop-webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cheeseshop-webapp
    spec:
      containers:
      - name: cheeseshop-webapp
        image: container-registry.dev.ibmesports.com/cheeseshop-webapp:$IMAGE_TAG
        imagePullPolicy: Always
        env:
        - name: SQL_HOST
          valueFrom:
            secretKeyRef:
             name: cheeseshop
             key: sql-host
        - name: SQL_PORT
          valueFrom:
            secretKeyRef:
             name: cheeseshop
             key: sql-port
        - name: SQL_USER
          value: admin
        - name: SQL_DATABASE
          value: compose
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
             name: cheeseshop
             key: sql-password
        ports:
        - containerPort: 8081
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cheeseshop-ingress
spec:
  rules:
  - host: ibmesports.com
    http:
      paths:
      - path: /static
        backend:
          serviceName: cheeseshop-static-service
          servicePort: 8082
      - path: /
        backend:
          serviceName: cheeseshop-webapp-service
          servicePort: 8081
